// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package repositories

import (
	"expresso/configs/core"
	"expresso/pkg/repositories/models"
)

// Injectors from wire.go:

func InitUserRepo(app core.App, user *models.User) *User {
	repository := New(app)
	repositoriesUser := NewUserRepository(repository, user)
	return repositoriesUser
}

func InitUser(app core.App) *User {
	repository := New(app)
	user := NewUser(repository)
	return user
}
