output   = "./pkg/repositories/models"
wipe     = true
no-tests = true
add-global-variants = true
no-hooks = true
no-context = true
debug = true


[mysql]
    dbname  = "expresso"
    host    = "localhost"
    port    = 3306
    user    = "root"
    pass    = "root"
    sslmode = "false"
    blacklist = ["schema_migrations"]
